resources:
- name: gdsre-aws-ruby
  type: docker-image
  source:
    # FIXME: move to docker hub
    repository: ((readonly_private_ecr_repo_url))
    tag: gdsre-aws-ruby-latest

- name: ruby-2.6.1
  type: docker-image
  source:
    repository: ruby
    tag: "2.6.1"

- name: gdsre-aws-ruby-git
  type: git
  source:
    uri: https://github.com/alphagov/tech-ops.git
    branch: master
    paths:
    - reliability-engineering/dockerfiles/gdsre/aws-ruby

- name: build-gdsre-docker-pipeline
  type: git
  source:
    uri: https://github.com/alphagov/tech-ops.git
    branch: master
    paths:
    - reliability-engineering/pipelines/build-gdsre-docker.yml

jobs:
- name: selfupdate
  serial: true
  plan:
  - get: build-gdsre-docker-pipeline
    trigger: true
  - set_pipeline: build-gdsre-docker
    file: build-gdsre-docker-pipeline/reliability-engineering/pipelines/build-gdsre-docker.yml
- name: build-gdsre-aws-ruby
  serial: true
  plan:
  - in_parallel:
    - get: gdsre-aws-ruby-git
      trigger: true
    - get: ruby-2.6.1
      trigger: true
      params: {save: true}
  - put: gdsre-aws-ruby
    params:
      build: gdsre-aws-ruby-git/reliability-engineering/dockerfiles/gdsre/aws-ruby
      load_bases: [ ruby-2.6.1 ]
    get_params: {skip_download: true}
