resources:
  - name: re-team-manual-git
    type: git
    source:
      uri: https://github.com/alphagov/re-team-manual.git
      branch: master

  - name: reliability-engineering-git
    type: git
    source:
      uri: https://github.com/alphagov/reliability-engineering.git
      branch: master

  - name: gds-way-git
    type: git
    source:
      uri: https://github.com/alphagov/gds-way.git
      branch: master

  - name: deploy-to-paas-docs-space
    type: cf
    source:
      api: https://api.cloud.service.gov.uk
      username: ((cf_user))
      password: ((cf_password))
      organization: gds-tech-ops
      space: docs

jobs:
  - name: deploy-re-team-manual
    serial: true
    plan:
      - get: re-team-manual-git
        trigger: true
      - task: bundle-re-team-manual
        timeout: 15m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdsre/aws-ruby
              tag: 2.6.1-3.0.1
          inputs:
            - name: re-team-manual-git
              path: repo
          outputs:
            - name: bundled
          run: &bundle
            path: sh
            dir: repo
            args:
            - -c
            - |
              apt-get update
              apt-get install -y nodejs
              bundle install --without development
              bundle exec middleman build
              cp -r . ../bundled/
      - put: deploy-to-paas-docs-space
        params:
          manifest: bundled/manifest.yml
          show_app_log: true
          path: bundled

  - name: deploy-reliability-engineering
    serial: true
    plan:
      - get: reliability-engineering-git
        trigger: true
      - task: bundle-reliability-engineering
        timeout: 15m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdsre/aws-ruby
              tag: 2.6.1-3.0.1
          inputs:
            - name: reliability-engineering-git
              path: repo
          outputs:
            - name: bundled
          run: *bundle
      - put: deploy-to-paas-docs-space
        params:
          manifest: bundled/manifest.yml
          show_app_log: true
          path: bundled

  - name: deploy-gds-way
    serial: true
    plan:
      - get: gds-way-git
        trigger: true
      - task: bundle-gds-way
        timeout: 15m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gdsre/aws-ruby
              tag: 2.6.1-3.0.1
          inputs:
            - name: gds-way-git
              path: repo
          outputs:
            - name: bundled
          run: *bundle
      - put: deploy-to-paas-docs-space
        params:
          manifest: bundled/manifest.yml
          show_app_log: true
          path: bundled
