platform: linux
image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest
inputs:
- name: repository
params:
  GPG_VERIFICATION_KEY:
  GPG_VERIFICATION_TAG:
run:
  path: sh
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "checking if we need to verify this tag..."
      if [ -z "${GPG_VERIFICATION_TAG}" ]; then
        echo "+------------------------------------------------------------------+"
        echo "| tag verification will be skipped as GPG_VERIFICATION_TAG not set |"
        echo "+------------------------------------------------------------------+"
        exit 0
      fi
      echo "configuring trusted keys..."
      echo "${GPG_VERIFICATION_KEY}" > key
      gpg --import key
      export GPG_TTY=$(tty)
      echo "trusted keys..."
      gpg --list-keys
      echo "verifying commit signed by a trusted key..."
      cd repository
      git tag --points-at HEAD
      git verify-commit HEAD
